obj-$(CONFIG_HARDKERNEL_UMP)		+= hardkernel_ump.o
obj-$(CONFIG_ODROID_U2_FAN)		+= odroidu2_fan.o

        EXTRA_CFLAGS += -Idrivers/video/mali/r3p2/ump \
                        -Idrivers/video/mali/r3p2/mali/common \
                        -Idrivers/video/mali/r3p2/mali/linux
                                                        