ZFS_MODULE_CFLAGS  = -I$(srctree)/include/zfs -I$(srctree)/include/spl 
ZFS_MODULE_CFLAGS += -include $(srctree)/spl_config.h -include $(srctree)/zfs_config.h
export ZFS_MODULE_CFLAGS

obj-$(CONFIG_ZFS) :=
obj-$(CONFIG_ZFS) +=  avl/
obj-$(CONFIG_ZFS) +=  nvpair/
obj-$(CONFIG_ZFS) +=  unicode/
obj-$(CONFIG_ZFS) +=  zcommon/
obj-$(CONFIG_ZFS) +=  zfs/
obj-$(CONFIG_ZFS) +=  zpios/
